### ISSUE TITLE
FT_Transformer - Attention weights

### ISSUE THREAD

**Issue by peterlee18** [lucidrains/tab-transformer-pytorch#17]
Thanks for these models. The FT_transformer is working well. Is there a way to extract the attention weights from the model. I understand these can be used to get feature importance.

**Comment by lucidrains** [comment]
@peterlee18 glad to hear it is working well! hope it is not too late, but you can now return all the attention maps by passing in `return_attn = True` on forward [as so](https://github.com/lucidrains/tab-transformer-pytorch/commit/582ebc801797199e6f7d3ae491981335f251e451#diff-82fca44d3316e0c04a31bad04114cfff1a8d47b8eb12d9f7397ba7272358f72eR183)

**Comment by peterlee18** [comment]
Thanks very much. Will give it try.

 

By the way, the FT_Transformer architecture is much more performant (than the Tab_Transformer)  when applied to insurance tubular data. Its makes NN competitive with GBMs and with different performance characteristics, it’s helpful in a simple weighted ensemble with GBMs.

**Comment by lucidrains** [comment]
@peterlee18 that is really interesting

if i find some more time, i'll improve on FT transformer with some of the latest findings, see if i can tip it over the edge

**Comment by lucidrains** [comment]
@peterlee18 how much data are you working with? (if you are allowed to say)

**Comment by peterlee18** [comment]
I’m experimenting with around 1m rows of data with around 30 features. Mixture of numerical and categorical. I have pre-converted the categorical features into embeddings other the number of dimensions gets too large. FT_Transformer is both memory and gpu intensive (that’s the down-side) so using quite small batch sizes (for insurance data use-case). Also in inference mode, I chunk up the data to get predictions out, otherwise we run out of memory.

**Comment by lucidrains** [comment]
@peterlee18 that's really cool! at my last job i did a lot of work with GBMs (training and deploying xgboost models mainly) and they were really hard to beat

glad to hear you were able to get competitive performance using attention!
