### ISSUE TITLE
The Paper describes one Embedding for each column

### ISSUE THREAD

**Issue by jaanisfehling** [lucidrains/tab-transformer-pytorch#20]
Hi,

In the TabTranformer paper it says:
 "Column embedding. For each categorical feature (col-
umn) i, we have an embedding lookup table eφi (.), for
i ∈ {1, 2, ..., m}. [...]"

In your source code, for both implementations you use one Lookup Table for all columns. 
Or am I missing something? I am still learning.

Thank you!

**Comment by lucidrains** [comment]
@jaanisfehling so i actually combined the entire lookup table into one embedding table, and then use offsets to fetch them all at once
